# fly.toml app configuration file generated for telegram-bot-tree on 2023-07-01T20:08:40+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegram-bot-tree"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
